spring:
  primary:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://database-2.cxmouqa8kd3e.ap-northeast-2.rds.amazonaws.com:3306/wind?serverTimezone=Asia/Seoul
      username: admin
      password: 'qweqwe123'
  secondary:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://rmq.cxmouqa8kd3e.ap-northeast-2.rds.amazonaws.com:3306/lsports?serverTimezone=Asia/Seoul
      username: admin
      password: 'qweqwe123'
springdoc:
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method # alpha(알파벳 오름차순), method(HTTP 메소드순)
    tags-sorter: alpha # 태그 정렬 기준
    path: /swagger-ui.html # html 문서 접속 경로
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation 펼치는 방식
    model-converters:
      pageable-converter:
        enabled: true
secret:
  api-key: "ehowl123123"